[package]
name = "perif-cli"
version = "0.1.0"
authors = ["Sebastian N. Kaupe <sebastian.kaupe@t-online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"